mengimportkan package yang kita butuhkan

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

Input data yang dimiliki

In [2]:
Nilai = pd.read_csv("https://raw.githubusercontent.com/trifarameliniaa/Proyek-Pemodelan/main/NilaiMahasiswa.csv")
print(Nilai)

    No Nama Mahasiswa  UTS  Tugas  UAS
0    1            Roy   89     90   75
1    2         Sintia   90     71   95
2    3          Iqbal   70     75   80
3    4          Dilan   45     65   59
4    5          Ratna   65     75   53
5    6          Merry   80     70   75
6    7           Rudi   90     85   81
7    8          Hafiz   70     70   73
8    9           Gede   96     93   85
9   10      Christian   60     55   48
10  11         Justin   45     60   58
11  12         Jesika   60     70   72
12  13            Ayu   85     90   88
13  14          Siska   52     68   55
14  15        Reitama   40     60   70


Melihat Informasi dari setiap Variable

In [3]:
Nilai.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   No              15 non-null     int64 
 1   Nama Mahasiswa  15 non-null     object
 2   UTS             15 non-null     int64 
 3   Tugas           15 non-null     int64 
 4   UAS             15 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 728.0+ bytes


Menentukan variabel mana yang akan diklusterkan

In [4]:
Nama = Nilai.iloc[:, 2:5]
print(Nama)

    UTS  Tugas  UAS
0    89     90   75
1    90     71   95
2    70     75   80
3    45     65   59
4    65     75   53
5    80     70   75
6    90     85   81
7    70     70   73
8    96     93   85
9    60     55   48
10   45     60   58
11   60     70   72
12   85     90   88
13   52     68   55
14   40     60   70


Mengubah variabel yang sebelumnya berbentuk data frame menjadi array

In [5]:
x_array = np.array(Nama)
print(x_array)

[[89 90 75]
 [90 71 95]
 [70 75 80]
 [45 65 59]
 [65 75 53]
 [80 70 75]
 [90 85 81]
 [70 70 73]
 [96 93 85]
 [60 55 48]
 [45 60 58]
 [60 70 72]
 [85 90 88]
 [52 68 55]
 [40 60 70]]


Menentukan jumlah klasternya, Misal menjadi 3 klaster

In [6]:
#Menentukan dan mengkonfigurasi fungsi kmeans
kmeans =KMeans(n_clusters = 3, random_state=123)
#Menentukan kluster dari data
kmeans.fit(x_array)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=123, tol=0.0001, verbose=0)

Mencari nilai pusat dari masing-masing klaster

In [7]:
print(kmeans.cluster_centers_)

[[90.         85.8        84.8       ]
 [51.16666667 63.83333333 57.16666667]
 [70.         71.25       75.        ]]


Kemudian tampilkan hasil klaster dan tambahkan kolom klaster kedalam data frame

In [8]:
#Menampilkan hasil kluster
print(kmeans.labels_)
#Menambahkan kolom "klaster" dalam data frame
Nama["klaster"] = kmeans.labels_
print(Nama)

[0 0 2 1 1 2 0 2 0 1 1 2 0 1 1]
    UTS  Tugas  UAS  klaster
0    89     90   75        0
1    90     71   95        0
2    70     75   80        2
3    45     65   59        1
4    65     75   53        1
5    80     70   75        2
6    90     85   81        0
7    70     70   73        2
8    96     93   85        0
9    60     55   48        1
10   45     60   58        1
11   60     70   72        2
12   85     90   88        0
13   52     68   55        1
14   40     60   70        1
